# https://taskfile.dev

version: "3"

includes:
  git:
    taskfile: ./node_modules/@northbridge-security/ai-toolkit/tasks/git.yml
    dir: .
  json:
    taskfile: ./node_modules/@northbridge-security/ai-toolkit/tasks/json.yml
    dir: .
  yaml:
    taskfile: ./node_modules/@northbridge-security/ai-toolkit/tasks/yaml.yml
    aliases:
      - yml
    dir: .
  markdown:
    taskfile: ./node_modules/@northbridge-security/ai-toolkit/tasks/markdown.yml
    aliases:
      - md
    dir: .
  security:
    taskfile: ./node_modules/@northbridge-security/ai-toolkit/tasks/security.yml
    aliases:
      - s
    dir: .
  op:
    taskfile: ./node_modules/@northbridge-security/ai-toolkit/tasks/onepassword.yml
    dir: .

vars:
  PROJECT_NAME: "cdn"

tasks:
  install:
    desc: "Install/upgrade required development tools"
    aliases: [i]
    silent: true
    cmds:
      - bun scripts/install.ts

  setup:repo:
    desc: "Configure GitHub repository secrets for CI/CD"
    aliases: [setup]
    silent: true
    cmds:
      - bun scripts/setup-repo.ts

  clear:
    desc: "Remove caches and temp files, reinstall dependencies"
    aliases: [cls]
    silent: true
    cmds:
      - |
        set -euo pipefail

        GREEN='\033[0;32m'
        CYAN='\033[0;36m'
        NC='\033[0m'

        echo -e "${CYAN}Clearing caches and temp files${NC}"

        for dir in .tmp .logs .turbo coverage dist build node_modules/.cache; do
          if [ -d "$dir" ]; then
            rm -rf "$dir"
            echo -e "  ${GREEN}removed${NC} $dir"
          fi
        done

        # Remove TypeScript build info
        find . -name '*.tsbuildinfo' -not -path './node_modules/*' -delete 2>/dev/null && \
          echo -e "  ${GREEN}removed${NC} *.tsbuildinfo" || true

        # Remove node_modules to guarantee clean dependency tree
        if [ -d "node_modules" ]; then
          rm -rf node_modules
          echo -e "  ${GREEN}removed${NC} node_modules"
        fi

        echo ""
      - task: install

  default:
    desc: "Show available cdn tasks"
    aliases: [help, h]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        YELLOW='\033[0;33m'
        BLUE='\033[0;34m'
        CYAN='\033[0;36m'
        BOLD='\033[1m'
        NC='\033[0m'

        echo -e "${BOLD}@lekman/cdn — Edge Cache CDN API${NC}"
        echo ""
        echo "Command                            Alias     Description"
        echo "────────────────────────────────────────────────────────────────────────────────"
        echo -e "${BOLD}Setup:${NC}"
        echo -e "  ${GREEN}task install${NC}                     ${YELLOW}i${NC}         Install/upgrade required tools"
        echo -e "  ${GREEN}task clear${NC}                       ${YELLOW}cls${NC}       Remove caches, reinstall dependencies"
        echo -e "  ${GREEN}task setup:repo${NC}                  ${YELLOW}setup${NC}     Configure GitHub repo secrets"
        echo ""
        echo -e "${BOLD}Development:${NC}"
        echo -e "  ${GREEN}task lint${NC}                        ${YELLOW}l${NC}         Run linting checks"
        echo -e "  ${GREEN}task format${NC}                      ${YELLOW}fmt${NC}       Format code"
        echo -e "  ${GREEN}task typecheck${NC}                   ${YELLOW}tc${NC}        Run TypeScript type checking"
        echo -e "  ${GREEN}task test${NC}                        ${YELLOW}t${NC}         Run tests"
        echo -e "  ${GREEN}task test:coverage${NC}               ${YELLOW}cov${NC}       Run tests with coverage report"
        echo -e "  ${GREEN}task test:iq${NC}                     ${YELLOW}iq${NC}        IQ: deployed resources match spec"
        echo -e "  ${GREEN}task test:oq${NC}                     ${YELLOW}oq${NC}        OQ: services operational/healthy"
        echo -e "  ${GREEN}task quality${NC}                     ${YELLOW}q${NC}         Run all quality checks"
        echo ""
        echo -e "${BOLD}Security:${NC}"
        echo -e "  ${GREEN}task security:scan${NC}               ${YELLOW}s:s${NC}       Run semgrep security scanner"
        echo ""
        echo -e "${BOLD}Infrastructure:${NC}"
        echo -e "  ${GREEN}task oidc:setup${NC}                  ${YELLOW}oidc${NC}      Setup Azure OIDC for CI/CD"
        echo -e "  ${GREEN}task infra:init${NC}                  ${YELLOW}init${NC}      Initialize Pulumi stacks (dev + prod)"
        echo -e "  ${GREEN}task infra:bootstrap${NC}             ${YELLOW}boot${NC}      Bootstrap consumption plan (MSDN)"
        echo -e "  ${GREEN}task infra:preview${NC}               ${YELLOW}pre${NC}       Preview changes (default: dev)"
        echo -e "  ${GREEN}task infra:up${NC}                    ${YELLOW}up${NC}        Deploy to Azure (default: dev)"
        echo -e "  ${GREEN}task infra:down${NC}                  ${YELLOW}down${NC}      Destroy resources (default: dev)"
        echo -e "  ${GREEN}task infra:refresh${NC}               ${YELLOW}ref${NC}       Refresh Pulumi state from Azure"
        echo -e "  ${GREEN}task infra:outputs${NC}               ${YELLOW}out${NC}       Show stack outputs as JSON"
        echo ""
        echo -e "${BOLD}Claude Code:${NC}"
        echo -e "  ${GREEN}task claude:plan${NC}                 ${YELLOW}plan${NC}      Open latest Claude plan in IDE"
        echo ""
        echo -e "${BOLD}Utilities:${NC}"
        echo -e "  ${GREEN}task warp${NC}                        ${YELLOW}w${NC}         Open repo in Warp terminal"
        echo -e "  ${GREEN}task warp:claude${NC}                 ${YELLOW}wc${NC}        Open Claude Code in Warp"
        echo ""
        echo -e "${BOLD}Task Libraries:${NC}"
        echo -e "  ${GREEN}task git:<command>${NC}                         Git & GitHub operations"
        echo -e "  ${GREEN}task json:<command>${NC}                        JSON linting & validation"
        echo -e "  ${GREEN}task yaml:<command>${NC}              ${YELLOW}yml${NC}       YAML linting & validation"
        echo -e "  ${GREEN}task markdown:<command>${NC}          ${YELLOW}md${NC}        Markdown linting & validation"
        echo -e "  ${GREEN}task security:<command>${NC}          ${YELLOW}s${NC}         Security scanning tools"
        echo -e "  ${GREEN}task op:<command>${NC}                          1Password secret resolution"
        echo ""
        echo -e "${BLUE}Run 'task --list' to see all available tasks${NC}"

  lint:
    desc: "Run linting checks"
    aliases: [l]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        NC='\033[0m'

        echo -e "${GREEN}Running linting...${NC}"
        bunx turbo run lint

  format:
    desc: "Format code"
    aliases: [fmt]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        NC='\033[0m'

        echo -e "${GREEN}Formatting code...${NC}"
        bun run format

  typecheck:
    desc: "Run TypeScript type checking"
    aliases: [tc]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        NC='\033[0m'

        echo -e "${GREEN}Type checking...${NC}"
        bunx turbo run typecheck

  test:
    desc: "Run tests"
    aliases: [t]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        NC='\033[0m'

        echo -e "${GREEN}Running tests...${NC}"
        bunx turbo run test

  test:coverage:
    desc: "Run tests with coverage report"
    aliases: [cov]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        CYAN='\033[0;36m'
        NC='\033[0m'

        echo -e "${GREEN}Running unit tests with coverage...${NC}"
        bunx turbo run test:coverage
        echo ""
        echo -e "${CYAN}Coverage report generated:${NC}"
        echo -e "  LCOV: ${GREEN}coverage/lcov.info${NC}"

  test:iq:
    desc: "Run IQ tests: deployed resources match spec (usage: task test:iq -- dev)"
    aliases: [iq]
    silent: true
    vars:
      STACK: '{{.CLI_ARGS | default "dev"}}'
    deps: [infra:check-prereqs]
    cmds:
      - |
        set -euo pipefail
        GREEN='\033[0;32m'
        CYAN='\033[0;36m'
        NC='\033[0m'
        echo -e "${GREEN}Running IQ tests against ${CYAN}{{.STACK}}${NC}"
        STACK="{{.STACK}}" bun test tests/iq/

  test:oq:
    desc: "Run OQ tests: services operational and healthy (usage: task test:oq -- dev)"
    aliases: [oq]
    silent: true
    vars:
      STACK: '{{.CLI_ARGS | default "dev"}}'
    deps: [infra:check-prereqs]
    cmds:
      - |
        set -euo pipefail
        GREEN='\033[0;32m'
        CYAN='\033[0;36m'
        NC='\033[0m'
        echo -e "${GREEN}Running OQ tests against ${CYAN}{{.STACK}}${NC}"
        STACK="{{.STACK}}" bun test tests/oq/

  ide:open:
    desc: "Open a file in the active IDE (detects running editor)"
    internal: true
    silent: true
    cmds:
      - |
        set -euo pipefail
        FILE="{{.FILE}}"
        if [ -z "$FILE" ]; then
          echo "Error: FILE variable not set"
          exit 1
        fi

        # Known CLI paths (macOS installs to /usr/local/bin)
        CLI_INSIDERS="/usr/local/bin/code-insiders"
        CLI_CODE="/usr/local/bin/code"
        CLI_CURSOR="/usr/local/bin/cursor"

        # Detect running IDE from process list (most specific first)
        IDE=""
        if pgrep -f "Code - Insiders" &>/dev/null && [ -x "$CLI_INSIDERS" ]; then
          IDE="$CLI_INSIDERS"
        elif pgrep -f "Cursor Helper" &>/dev/null && [ -x "$CLI_CURSOR" ]; then
          IDE="$CLI_CURSOR"
        elif pgrep -f "Visual Studio Code.app" &>/dev/null && [ -x "$CLI_CODE" ]; then
          IDE="$CLI_CODE"
        fi

        # Fall back to whatever CLI is available
        if [ -z "$IDE" ]; then
          for cmd in "$CLI_INSIDERS" "$CLI_CURSOR" "$CLI_CODE"; do
            if [ -x "$cmd" ]; then
              IDE="$cmd"
              break
            fi
          done
        fi

        if [ -n "$IDE" ]; then
          "$IDE" --reuse-window "$FILE"
        elif [ -n "${EDITOR:-}" ]; then
          $EDITOR "$FILE"
        else
          open "$FILE"
        fi

  claude:plan:
    desc: "Open the latest Claude Code plan"
    aliases: [plan]
    silent: true
    cmds:
      - bun scripts/open-plan.ts

  warp:
    desc: "Open repo in Warp terminal (blue tab)"
    aliases: [w, terminal]
    silent: true
    cmds:
      - |
        set -euo pipefail
        NAME="{{.PROJECT_NAME}}-terminal"
        mkdir -p "$HOME/.warp/launch_configurations"
        printf '%s\n' \
          "---" \
          "name: $NAME" \
          "windows:" \
          "  - tabs:" \
          "      - title: {{.PROJECT_NAME}}" \
          "        color: blue" \
          "        layout:" \
          "          cwd: \"{{.ROOT_DIR}}\"" \
          "          is_focused: true" \
          > "$HOME/.warp/launch_configurations/$NAME.yml"
        open "warp://launch/$NAME"

  warp:claude:
    desc: "Open Claude Code in Warp (yellow tab)"
    aliases: [wc]
    silent: true
    cmds:
      - |
        set -euo pipefail
        NAME="{{.PROJECT_NAME}}-claude"
        mkdir -p "$HOME/.warp/launch_configurations"
        printf '%s\n' \
          "---" \
          "name: $NAME" \
          "windows:" \
          "  - tabs:" \
          "      - title: Claude" \
          "        color: yellow" \
          "        layout:" \
          "          cwd: \"{{.ROOT_DIR}}\"" \
          "          commands:" \
          "            - exec: claude -c" \
          "          is_focused: true" \
          > "$HOME/.warp/launch_configurations/$NAME.yml"
        open "warp://launch/$NAME"


  quality:
    desc: "Run all quality checks (lint, typecheck, security, test)"
    aliases: [q]
    silent: true
    cmds:
      - |
        GREEN='\033[0;32m'
        CYAN='\033[0;36m'
        NC='\033[0m'

        echo -e "${CYAN}Running Quality Checks${NC}"
        echo "---"
      - task: lint
      - task: typecheck
      - task: security:scan
      - task: test
      - |
        GREEN='\033[0;32m'
        NC='\033[0m'

        echo ""
        echo -e "${GREEN}✓${NC} All quality checks passed"

  # ---------------------------------------------------------------------------
  # Infrastructure (Pulumi)
  # ---------------------------------------------------------------------------

  infra:check-prereqs:
    desc: "Check infrastructure prerequisites (az, pulumi, login)"
    internal: true
    silent: true
    cmds:
      - |
        set -euo pipefail
        RED='\033[0;31m'
        CYAN='\033[0;36m'
        NC='\033[0m'

        if ! command -v pulumi &>/dev/null; then
          echo -e "${RED}Error:${NC} Pulumi is not installed."
          echo -e "  Install: ${CYAN}brew install pulumi${NC}"
          echo -e "  Or run:  ${CYAN}task install${NC}"
          exit 1
        fi

        if ! command -v az &>/dev/null; then
          echo -e "${RED}Error:${NC} Azure CLI (az) is not installed."
          echo -e "  Install: ${CYAN}brew install azure-cli${NC}"
          echo -e "  Or run:  ${CYAN}task install${NC}"
          exit 1
        fi

        if ! az account show &>/dev/null 2>&1; then
          echo -e "${RED}Error:${NC} Not logged in to Azure."
          echo -e "  Run: ${CYAN}az login${NC}"
          exit 1
        fi

        cd infra
        if ! pulumi whoami &>/dev/null 2>&1; then
          echo -e "${RED}Error:${NC} Not logged in to Pulumi."
          echo -e "  Run: ${CYAN}pulumi login${NC}"
          exit 1
        fi

  infra:init:
    desc: "Initialize Pulumi stacks (dev and prod)"
    aliases: [init]
    silent: true
    dir: infra
    deps: [infra:check-prereqs]
    cmds:
      - |
        set -euo pipefail
        GREEN='\033[0;32m'
        CYAN='\033[0;36m'
        NC='\033[0m'

        echo -e "${CYAN}Initializing Pulumi stacks${NC}"
        pulumi stack init dev 2>/dev/null || echo -e "${GREEN}dev stack already exists${NC}"
        pulumi stack init prod 2>/dev/null || echo -e "${GREEN}prod stack already exists${NC}"
        echo -e "${GREEN}✓${NC} Stacks initialized"

  infra:bootstrap:
    desc: "Bootstrap consumption plan on MSDN subscription (usage: task infra:bootstrap -- dev)"
    aliases: [boot]
    silent: true
    vars:
      STACK: '{{.CLI_ARGS | default "dev"}}'
    deps: [infra:check-prereqs]
    cmds:
      - bun scripts/infra-bootstrap.ts {{.STACK}}

  infra:preview:
    desc: "Preview infrastructure changes (usage: task infra:preview -- dev)"
    aliases: [pre]
    silent: true
    dir: infra
    vars:
      STACK: '{{.CLI_ARGS | default "dev"}}'
    deps: [infra:check-prereqs]
    cmds:
      - |
        set -euo pipefail
        GREEN='\033[0;32m'
        CYAN='\033[0;36m'
        NC='\033[0m'
        echo -e "${CYAN}Previewing infrastructure changes for ${GREEN}{{.STACK}}${NC}"
        pulumi preview -s "{{.STACK}}" --policy-pack security/policy-pack

  infra:up:
    desc: "Deploy infrastructure to Azure (usage: task infra:up -- dev)"
    aliases: [up]
    silent: true
    dir: infra
    vars:
      STACK: '{{.CLI_ARGS | default "dev"}}'
    deps: [infra:check-prereqs]
    cmds:
      - |
        set -euo pipefail
        pulumi up -s "{{.STACK}}" --yes --skip-preview --suppress-outputs --policy-pack security/policy-pack

  infra:down:
    desc: "Destroy infrastructure on Azure (usage: task infra:down -- dev)"
    aliases: [down]
    silent: true
    dir: infra
    vars:
      STACK: '{{.CLI_ARGS | default "dev"}}'
    deps: [infra:check-prereqs]
    cmds:
      - |
        set -euo pipefail
        pulumi destroy -s "{{.STACK}}" --yes --skip-preview --suppress-outputs

  infra:refresh:
    desc: "Refresh Pulumi state from Azure (usage: task infra:refresh -- dev)"
    aliases: [ref]
    silent: true
    dir: infra
    vars:
      STACK: '{{.CLI_ARGS | default "dev"}}'
    deps: [infra:check-prereqs]
    cmds:
      - |
        set -euo pipefail
        pulumi refresh -s "{{.STACK}}" --skip-preview --clear-pending-creates --suppress-outputs --yes

  infra:outputs:
    desc: "Show stack outputs as JSON (usage: task infra:outputs -- dev)"
    aliases: [out]
    silent: true
    dir: infra
    vars:
      STACK: '{{.CLI_ARGS | default "dev"}}'
    deps: [infra:check-prereqs]
    cmds:
      - pulumi stack output -s "{{.STACK}}" --json

  oidc:setup:
    desc: "Setup Azure OIDC for CI/CD: app registration, federated credentials, role assignment, GitHub variables"
    aliases: [oidc]
    silent: true
    cmds:
      - bun scripts/oidc-setup.ts
