name: cdn-infra
description: Edge Cache CDN Azure infrastructure (Storage, Cosmos DB, Functions, APIM API)
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: azure-typescript
